default:
  image: docker:25.0.3-dind
  before_script:
    - dockerd -l fatal &
    - sleep 5

variables:
  TAG: qli-2.1
  KUBERNETES_CPU_REQUEST: 60
  KUBERNETES_MEMORY_REQUEST: 128G
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 300G

build-x86:
  stage: build
  tags:
    - amd64-runner
  parallel:
    matrix:
      - MACHINE: shikra-evk
        DISTRO: qcom-distro qcom-distro-sota
  script:
    - ARCH="x86"
    - docker build -t clo-release-worker .
    - docker run clo-release-worker --tag ${TAG} --machine ${MACHINE} --distro ${DISTRO} --arch ${ARCH} --art-url "$ART_PLAT_URL" --art-user "$ART_PLAT_USER" --art-pass "$ART_PLAT_PASS" --upload
