default:
  image: docker:25.0.3-dind   # Using Docker-in-Docker image
  before_script:
    - dockerd -l fatal &      # Start Docker daemon in background
    - sleep 5                 # Wait for Docker daemon to initialize
  tags:
    - amd64-runner            # Specify the runner tag

# Global variables for the pipeline
variables:
  # Kubernetes resource requests
  KUBERNETES_CPU_REQUEST: 60
  KUBERNETES_MEMORY_REQUEST: 256G
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 500G

  # Define variables for easier maintenance and updates
  QCOM_RELEASE: qli-2.0-rc2
  ARCH: x86
  DOWNLOAD_SERVER: 0

build:
  stage: build
  before_script:
    - apk add --update curl && apk add --update git tar unzip zip && rm -rf /var/cache/apk/*
    - dockerd -l fatal &
    # - docker login -u "$ART_DOCKER_USER" -p "$ART_DOCKER_PASS" $ART_DOCKER_REG
    # Installing JFrog CLI
    - curl -fL https://install-cli.jfrog.io | sh
    - chmod +x /usr/local/bin/jf
    # Configure artifactory instance with JFrog CLI
    - pwd
    - projFolder=$(pwd)
    # - cd /usr/local/bin/
    - /usr/local/bin/jf --version
    - /usr/local/bin/jf c add artifactory-server --url=$ART_PLAT_URL --user=$ART_PLAT_USER --password=$ART_PLAT_PASS
    - /usr/local/bin/jf rt ping

  script:
    # Define variables for the build
    #- QCOM_RELEASE=qli-2.0-rc1
    - DOCKER_TAG="${QCOM_RELEASE}_22.04"
    - URL="https://github.com/qualcomm-linux"
    - BRANCH="qli-2.0-rc2"
    - PROJECT="meta-qcom-releases"
    - MACHINE="rb3gen2-core-kit"
    #- ARCH="arm"
    - DISTRO="qcom-distro-prop-image"
    - IMAGE="qcom-multimedia-image"
    - USER=lnxbuild         # Match the USER in Dockerfile
    - UID=2366345           # Match the UID in Dockerfile
    - GID=2366345           # Match the GID in Dockerfile
    - WORK_DIR="/home/${USER}/app"

    # Docker Build & Run
    - docker build --build-arg USER=${USER} --build-arg UID=${UID} --build-arg GID=${GID} --no-cache -t ${DOCKER_TAG} .
    - docker run --name build ${DOCKER_TAG} -u ${URL} -b ${BRANCH} -p ${PROJECT} -M ${MACHINE} -D ${DOWNLOAD_SERVER} -d ${DISTRO} -i ${IMAGE} -w "${WORK_DIR}/${DOCKER_TAG}" -a ${ARCH}

    # Define a reusable function for artifacts copy & zip it and upload to artifactory
    # This reduces code duplication and improves maintainability

    - |
      echo "Setting up artifacts copy, zip and upload function..."
      create_artifact_zipit_and_upload(){
        #set -euo pipefail
        local machine_name=$1
        
        #****************
        mkdir -p /rpm
        mkdir -p /images/${machine_name}
        mkdir -p /images/backup/${machine_name}
        #******************
        
             
        #************
        docker cp -L build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/images/${machine_name}/. /images/backup/${machine_name}/
        #************
        
        docker cp build:${WORK_DIR}/${DOCKER_TAG}/NOTICE /images/${machine_name}/
        docker cp build:${WORK_DIR}/${DOCKER_TAG}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/
        
        #*****************
        real_path=$(readlink "/images/backup/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz")
        cp /images/backup/${machine_name}/${real_path} /images/${machine_name}/
        tar -xzvf /images/${machine_name}/${real_path} -C /images/${machine_name}
        rm -f /images/${machine_name}/${real_path}
        real_path=$(readlink "/images/backup/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz")
        cp /images/backup/${machine_name}/${real_path} /images/${machine_name}/
        tar -xzvf /images/${machine_name}/${real_path} -C /images/${machine_name}
        rm -f /images/${machine_name}/${real_path}
        rm -rf /images/backup/${machine_name}
        #******************

        #*******************
        zip -r ${QCOM_RELEASE}-qcom-multimedia-image.zip /images/${machine_name}/NOTICE /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/qcom-multimedia-image-${machine_name}
        zip -r ${QCOM_RELEASE}-qcom-multimedia-proprietary-image.zip /images/${machine_name}/NOTICE /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}
        #********************
        /usr/local/bin/jf rt ping
        /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive "${QCOM_RELEASE}-*.zip" qli-ci/flashable-binaries/meta-qcom/${machine_name}/
        rm -f ${QCOM_RELEASE}-*.zip
      }
    - |
      echo "Setting up artifacts and sdk copy, zip and upload function..."
      create_artifact_and_sdk_zipit_and_upload(){
        #set -euo pipefail
        local machine_name=$1
        #****************
        mkdir -p /rpm
        mkdir -p /images/${machine_name}
        mkdir -p /images/backup/${machine_name}
        #******************
        mkdir -p /images/${machine_name}/sdk
        if [ "$DOWNLOAD_SERVER" == 1 ]; then
          mkdir -p /downloads
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/downloads/. /downloads
          /usr/local/bin/jf rt u --detailed-summary --flat=false --include-dirs --recursive "/downloads/(**)" "qli-ci/downloads/{1}"
        else
          #mkdir -p /downloads
               
          #************
          docker cp -L build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/images/${machine_name}/. /images/backup/${machine_name}/
          #************
        
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/sdk/. /images/${machine_name}/sdk/
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/NOTICE /images/${machine_name}/
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/
        
          #*****************
          real_path=$(readlink "/images/backup/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz")
          cp /images/backup/${machine_name}/${real_path} /images/${machine_name}/
          tar -xzvf /images/${machine_name}/${real_path} -C /images/${machine_name}
          rm -f /images/${machine_name}/${real_path}
          real_path=$(readlink "/images/backup/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz")
          cp /images/backup/${machine_name}/${real_path} /images/${machine_name}/
          tar -xzvf /images/${machine_name}/${real_path} -C /images/${machine_name}
          rm -f /images/${machine_name}/${real_path}
          rm -rf /images/backup/${machine_name}
          #******************

          #*******************
          zip -r ${QCOM_RELEASE}-qcom-multimedia-image.zip /images/${machine_name}/NOTICE /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/qcom-multimedia-image-${machine_name}
          zip -r ${QCOM_RELEASE}-qcom-multimedia-proprietary-image.zip /images/${machine_name}/NOTICE /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}
          #********************
        
          zip -r ${ARCH}-${QCOM_RELEASE}-esdk.zip /images/${machine_name} /images/${machine_name}/sdk -i /images/${machine_name}/sdk/*-toolchain-ext-*.sh -i /images/${machine_name}/NOTICE -i /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf
          zip -r ${ARCH}-${QCOM_RELEASE}-standardsdk.zip /images/${machine_name} /images/${machine_name}/sdk -i /images/${machine_name}/sdk/*-toolchain-*.sh -x /images/${machine_name}/sdk/*-toolchain-ext-*.sh -i /images/${machine_name}/NOTICE -i /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf
        
          /usr/local/bin/jf rt ping
          /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive "${QCOM_RELEASE}-*.zip" qli-ci/flashable-binaries/meta-qcom/${machine_name}/
          rm -f ${QCOM_RELEASE}-*.zip
          /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive "${ARCH}-${QCOM_RELEASE}-*.zip" qli-ci/flashable-binaries/meta-qcom/${machine_name}/
          rm -f x86-${QCOM_RELEASE}-*.zip
        fi
      } 
    - |
      echo "Setting up artifacts and sdk copy, zip and upload function..."
      create_artifacts_and_upload(){
        #set -euo pipefail
        local machine_name=$1
        #****************
        mkdir -p /images/${machine_name}
        mkdir -p /images/backup/${machine_name}
        #******************
        if [ "$DOWNLOAD_SERVER" == 1 ] && [ "$machine_name" == "qcom-armv8a" ] && [ "$ARCH" == "x86" ]; then
          mkdir -p /downloads
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/downloads/. /downloads
          /usr/local/bin/jf rt u --detailed-summary --flat=false --include-dirs --recursive "/downloads/(**)" "qli-ci/downloads/main/{1}"
        elif [ "$DOWNLOAD_SERVER" == 0 ] && [ "$machine_name" == "qcom-armv8a" ] && [ "$ARCH" == "arm" ]; then
          mkdir -p /images/${machine_name}/sdk
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/sdk/. /images/${machine_name}/sdk/
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/NOTICE /images/${machine_name}/
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/

          zip -r ${ARCH}-${QCOM_RELEASE}-esdk.zip /images/${machine_name} /images/${machine_name}/sdk -i /images/${machine_name}/sdk/*-toolchain-ext-*.sh -i /images/${machine_name}/NOTICE -i /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf
          zip -r ${ARCH}-${QCOM_RELEASE}-standardsdk.zip /images/${machine_name} /images/${machine_name}/sdk -i /images/${machine_name}/sdk/*-toolchain-*.sh -x /images/${machine_name}/sdk/*-toolchain-ext-*.sh -i /images/${machine_name}/NOTICE -i /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf

          /usr/local/bin/jf rt ping
          /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive "${ARCH}-${QCOM_RELEASE}-*.zip" qli-ci/flashable-binaries/meta-qcom/${machine_name}/
          rm -f x86-${QCOM_RELEASE}-*.zip
        else
          #mkdir -p /downloads
          mkdir -p /rpm
              
          #************
          docker cp -L build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/images/${machine_name}/. /images/backup/${machine_name}/
          #************
          if [ "$machine_name" == "qcom-armv8a" ]; then
            mkdir -p /images/${machine_name}/sdk
            docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/sdk/. /images/${machine_name}/sdk/
          fi
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/NOTICE /images/${machine_name}/
          docker cp build:${WORK_DIR}/${DOCKER_TAG}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/
        
          #*****************
          real_path=$(readlink "/images/backup/${machine_name}/qcom-multimedia-image-${machine_name}.rootfs.qcomflash.tar.gz")
          cp /images/backup/${machine_name}/${real_path} /images/${machine_name}/
          tar -xzvf /images/${machine_name}/${real_path} -C /images/${machine_name}
          rm -f /images/${machine_name}/${real_path}
          real_path=$(readlink "/images/backup/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}.rootfs.qcomflash.tar.gz")
          cp /images/backup/${machine_name}/${real_path} /images/${machine_name}/
          tar -xzvf /images/${machine_name}/${real_path} -C /images/${machine_name}
          rm -f /images/${machine_name}/${real_path}
          rm -rf /images/backup/${machine_name}
          #******************

          #*******************
          zip -r ${QCOM_RELEASE}-qcom-multimedia-image.zip /images/${machine_name}/NOTICE /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/qcom-multimedia-image-${machine_name}
          zip -r ${QCOM_RELEASE}-qcom-multimedia-proprietary-image.zip /images/${machine_name}/NOTICE /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf /images/${machine_name}/qcom-multimedia-proprietary-image-${machine_name}
          #********************
          if [ "$machine_name" == "qcom-armv8a" ]; then
            zip -r ${ARCH}-${QCOM_RELEASE}-esdk.zip /images/${machine_name} /images/${machine_name}/sdk -i /images/${machine_name}/sdk/*-toolchain-ext-*.sh -i /images/${machine_name}/NOTICE -i /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf
            zip -r ${ARCH}-${QCOM_RELEASE}-standardsdk.zip /images/${machine_name} /images/${machine_name}/sdk -i /images/${machine_name}/sdk/*-toolchain-*.sh -x /images/${machine_name}/sdk/*-toolchain-ext-*.sh -i /images/${machine_name}/NOTICE -i /images/${machine_name}/NO.LOGIN.BINARY.LICENSE.QTI.pdf
          fi
          /usr/local/bin/jf rt ping
          /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive "${QCOM_RELEASE}-*.zip" qli-ci/flashable-binaries/meta-qcom/${machine_name}/
          rm -f ${QCOM_RELEASE}-*.zip
          if [ "$machine_name" == "qcom-armv8a" ]; then
            /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive "${ARCH}-${QCOM_RELEASE}-*.zip" qli-ci/flashable-binaries/meta-qcom/${machine_name}/
            rm -f x86-${QCOM_RELEASE}-*.zip
            docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/rpm/. /rpm
            /usr/local/bin/jf rt u --detailed-summary --flat=false --include-dirs --recursive "/rpm/(**)" "qli-yocto-rpm/${QCOM_RELEASE}/rpm/{1}"
          fi
        fi
      }   
    - echo "Processing Copy, zip and upload for different machines:$DOCKER_TAG:$BRANCH"

    #*********************
    - |
      if [ "$ARCH" == "x86" ]; then
        if [ "$DOWNLOAD_SERVER" == 1 ]; then
          create_artifacts_and_upload "qcom-armv8a"
        else
          create_artifacts_and_upload "rb3gen2-core-kit"
          create_artifacts_and_upload "iq-8275-evk"
          create_artifacts_and_upload "iq-9075-evk"
          create_artifacts_and_upload "iq-615-evk"
          create_artifacts_and_upload "qcom-armv8a"
        fi
      else
        create_artifacts_and_upload "qcom-armv8a"
      fi        
    #- create_artifact_zipit_and_upload "rb3gen2-core-kit"
    #- create_artifact_zipit_and_upload "iq-8275-evk"
    #- create_artifact_zipit_and_upload "iq-9075-evk"
    #- create_artifact_zipit_and_upload "iq-615-evk"
    #**********************
    
    # - create_artifact_zipit_and_upload "qcs615-ride"
    # - create_artifact_zipit_and_upload "iq-x7181-evk"
    #- create_artifact_and_sdk_zipit_and_upload "qcom-armv8a"

    #********************
    #- mkdir -p /rpm
    #- docker cp build:${WORK_DIR}/qli-2.0-rc1_22.04/build/tmp/deploy/rpm/. /rpm
    #- /usr/local/bin/jf rt ping
    #- |
    #  if [ "$ARCH" == "x86" ]; then
    #    if [ "$DOWNLOAD_SERVER" == 0 ]; then
    #      docker cp build:${WORK_DIR}/${DOCKER_TAG}/build/tmp/deploy/rpm/. /rpm
    #      /usr/local/bin/jf rt u --detailed-summary --flat=false --include-dirs --recursive "/rpm/(**)" "qli-yocto-rpm/${QCOM_RELEASE}/rpm/{1}"
    #    fi
    #  fi    
    #- /usr/local/bin/jf rt u --detailed-summary --flat=false --include-dirs --recursive "/rpm/(**)" "qli-yocto-rpm/${QCOM_RELEASE}/rpm/{1}"
    #- mkdir -p /downloads
    #- docker cp build:${WORK_DIR}/qli-2.0-rc1_22.04/build/downloads/. /downloads
    #- /usr/local/bin/jf rt ping
    #- /usr/local/bin/jf rt u --detailed-summary --flat=false --include-dirs --recursive "/downloads/(**)" "qli-ci/downloads/{1}"
    #*********************
    - docker rm build